name: Output information on issues

on:
  issues:
    types: [opened, edited, closed]

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - name: Output GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
